# ---- data ------
data:
  train_path: "data/train-small.jsonl"
  eval_path: "data/validate-small.jsonl"
  text_key: "text"
  max_seq_len: 2048
  shuffle: true


# ---- training ------
train:
  output_dir: "outputs/gemma3n_qlora_sft"
  num_train_epochs: 0
  max_steps: 8000
  per_device_train_batch_size: 8
  gradient_accumulation_steps: 8
  eval_strategy: "steps"
  logging_steps: 50
  eval_steps: 200
  save_steps: 1000
  save_total_limit: 2
  warmup_ratio: 0.03
  learning_rate: 2.0e-5
  weight_decay: 0.01
  lr_scheduler_type: "linear"
  seed: 3407
  bf16: true
  fp16: false
  gradient_checkpointing: true
  report_to: ["wandb"]
  optim: "adamw_8bit"

lora:
  r: 8
  alpha: 16
  dropout: 0.05
  bias: "none"
  target_modules: ["q_proj","k_proj","v_proj","o_proj","gate_proj","up_proj","down_proj"]

# ---- model/base ------
model:
  base_repo: "unsloth/gemma-3n-E4B-it"
  attn_impl: "flash_attention_2"
  use_unsloth_compile: true

# ---- misc ------
misc:
  project: "gemma3n-qlora-sft"
  run_name: "baseline"
  push_to_hub: false
  local_rank: -1